/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1/userguide/building_java_projects.html
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.4.31"
    id("org.openapi.generator") version "5.1.1"

    `java-library`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    testImplementation("org.jetbrains.kotlin:kotlin-test")

    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

}

openApiGenerate {

    generatorName.set("kotlin")
    inputSpec.set("$rootDir/specs/deepgram-v2.0.yaml")
    outputDir.set("$buildDir/generated")
    apiPackage.set("com.waltersson.deepgram.api")
    invokerPackage.set("com.waltersson.deepgram.invoker")
    modelPackage.set("com.waltersson.deepgram.model")
    configOptions.put("dateLibrary", "java8")
}