openapi: 3.0.0
servers:
  - url: 'https://api.deepgram.com/v1'
info:
  version: 1.0.0
  title: Deepgram API
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /projects:
    get:
      operationId: getProjects
      description: 'Retrieves basic information about the specified project.'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Projects'
  /projects/{project_id}:
    get:
      operationId: getProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    patch:
      operationId: updateProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectUpdate'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Projects:
      title: Projects
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    Project:
      title: Project
      properties:
        name:
          type: string
          description: 'Name of project'
        company:
          type: string
          description: 'Name of company'
        project_id:
          type: string
    ProjectUpdate:
      title: Project update
      properties:
        name:
          type: string
          description: 'Name of project'
        company:
          type: string
          description: 'Name of company'
    MessageResponse:
      title: Response message
      properties:
        message:
          type: string