openapi: 3.0.0
servers:
  - url: 'https://api.deepgram.com/v1'
info:
  version: 1.0.0
  title: Deepgram API
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /projects:
    get:
      operationId: getProjects
      description: 'Retrieves basic information about the specified project.'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{project_id}:
    get:
      operationId: getProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
    patch:
      operationId: updateProject
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                company:
                  type: string
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Project:
      title: Project
      properties:
        name:
          type: string
          description: 'Name of project'
        company:
          type: string
          description: 'Name of company'